version: '3.8'

services:
  mockserver:
    image: mockserver/mockserver:mockserver-5.15.0
    container_name: meu_mockserver
    user: root
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
      - ./config:/config

